# Site settings

title: Alex's Tech Blog
email: alexinbeijing@gmail.com
description: Explorations in the world of coding
baseurl: "" # subpath
url: "" # base hostname & protocol
github_username:  alexdowad
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: false               # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:alexdowad@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/alexdowad"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
